/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador;
import Modelo.Serie;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;

/**
 *
 * @author Ángel Torada
 */
public class Añadir extends javax.swing.JDialog {

    //Variables
    //Crea e instancia la serie que se va a añadir
    private Serie serie = new Serie();
    //Crea el controlador que se instancia en el constructor y que ya tiene la lista cargada previamente
    private static Controlador c;

    public Añadir(java.awt.Frame parent, boolean modal, Controlador c) {
        super(parent, modal);
        initComponents();
        this.c = c;
        jSliderNota.setValue(5);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jLabelProductores = new javax.swing.JLabel();
        jLabelGenero = new javax.swing.JLabel();
        jLabelAnyo = new javax.swing.JLabel();
        jLabelTemporadas = new javax.swing.JLabel();
        jTextFieldTemporadas = new javax.swing.JTextField();
        jTextFieldAño = new javax.swing.JTextField();
        jTextFieldGenero = new javax.swing.JTextField();
        jTextFieldProductores = new javax.swing.JTextField();
        jTextFieldTitulo = new javax.swing.JTextField();
        jLabelNota = new javax.swing.JLabel();
        jSliderNota = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        jButtonAñadir = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelTitulo.setText("Título:");

        jLabelProductores.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelProductores.setText("Productores:");

        jLabelGenero.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelGenero.setText("Género:");

        jLabelAnyo.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelAnyo.setText("Año:");

        jLabelTemporadas.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelTemporadas.setText("Temporadas:");

        jLabelNota.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelNota.setText("Nota:");

        jSliderNota.setMajorTickSpacing(5);
        jSliderNota.setMaximum(10);
        jSliderNota.setMinorTickSpacing(1);
        jSliderNota.setPaintLabels(true);
        jSliderNota.setPaintTicks(true);
        jSliderNota.setSnapToTicks(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Añadir una Serie");

        jButtonAñadir.setText("Añadir");
        jButtonAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAñadirActionPerformed(evt);
            }
        });

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabelAnyo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelGenero, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelTitulo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelProductores, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldProductores)
                            .addComponent(jTextFieldGenero)
                            .addComponent(jTextFieldAño)
                            .addComponent(jTextFieldTitulo)))
                    .addComponent(jButtonAñadir)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelNota, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTemporadas))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jSliderNota, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jTextFieldTemporadas, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTitulo)
                    .addComponent(jTextFieldTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelProductores)
                    .addComponent(jTextFieldProductores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelGenero)
                    .addComponent(jTextFieldGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAnyo)
                    .addComponent(jTextFieldAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTemporadas)
                    .addComponent(jTextFieldTemporadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNota)
                    .addComponent(jSliderNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAñadir)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Botón de añadir, mira que todos los datos estén correctamente antes de añadirla.
    private void jButtonAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAñadirActionPerformed
        serie = llenaSerie();
        if (serie != null) {
            c.nuevo(serie);
            dispose();
        } else {
            jTextFieldTitulo.setText("");
            jTextFieldProductores.setText("");
            jTextFieldGenero.setText("");
            jTextFieldAño.setText("");
            jTextFieldTemporadas.setText("");
            jSliderNota.setValue(5);
        }
    }//GEN-LAST:event_jButtonAñadirActionPerformed

    //Botón de salir
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    //Método que se encarga de llenar devolver una serie con sus datos si está todo bien
    private Serie llenaSerie() {
        try {
            if (jTextFieldTitulo.getText() == null || "".equals(jTextFieldTitulo.getText())
                    || jTextFieldProductores.getText() == null || "".equals(jTextFieldProductores.getText())
                    || jTextFieldGenero.getText() == null || "".equals(jTextFieldGenero.getText())
                    || Integer.valueOf(jTextFieldAño.getText()) < 0
                    || Integer.valueOf(jTextFieldTemporadas.getText()) < 0) {
                JOptionPane.showMessageDialog(null, "Datos Incorrectos");
                serie = null;
                return serie;
            } else {
                Serie libroLlenaLibro = new Serie(jTextFieldTitulo.getText(), jTextFieldGenero.getText(), jTextFieldProductores.getText(), Integer.valueOf(jTextFieldAño.getText()), Integer.valueOf(jTextFieldTemporadas.getText()), jSliderNota.getValue());
                return libroLlenaLibro;
            }
        } catch (HeadlessException | NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Datos Incorrectos");
            serie = null;
            return serie;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Añadir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Añadir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Añadir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Añadir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Añadir dialog = new Añadir(new javax.swing.JFrame(), true, c);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAñadir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAnyo;
    private javax.swing.JLabel jLabelGenero;
    private javax.swing.JLabel jLabelNota;
    private javax.swing.JLabel jLabelProductores;
    private javax.swing.JLabel jLabelTemporadas;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JSlider jSliderNota;
    private javax.swing.JTextField jTextFieldAño;
    private javax.swing.JTextField jTextFieldGenero;
    private javax.swing.JTextField jTextFieldProductores;
    private javax.swing.JTextField jTextFieldTemporadas;
    private javax.swing.JTextField jTextFieldTitulo;
    // End of variables declaration//GEN-END:variables
}
